apiVersion: esx.vmware.com/v1alpha1
kind: HostConfiguration
metadata:
  name: keswick-host-config
  namespace: esx-system
spec:
  layertype: Incremental
  profile: |
    {
      "esx": {
        "network_vss": {
          "switches": [
            {
              "bridge": {
                "link_discovery_protocol": {
                  "operation": "LISTEN",
                  "protocol": "CDP"
                },
                "nics": [
                  "vmnic0"
                ]
              },
              "name": "vSwitch0",
              "policy": {
                "nic_teaming": {
                  "active_nics": [
                    "vmnic0"
                  ],
                  "link_criteria_beacon": "IGNORE",
                  "notify_switches": true,
                  "policy": "LOADBALANCE_SRCID",
                  "rolling_order": false,
                  "standby_nics": []
                },
                "security": {
                  "allow_promiscuous": false,
                  "forged_transmits": false,
                  "mac_changes": false
                }
              },
              "port_groups": [
                {
                  "name": "Management Network-2",
                  "policy": {
                    "nic_teaming": {
                      "active_nics": [
                        "vmnic0"
                      ],
                      "link_criteria_beacon": "IGNORE",
                      "notify_switches": true,
                      "policy": "LOADBALANCE_SRCID",
                      "rolling_order": false,
                      "standby_nics": []
                    }
                  },
                  "vlan_id": 0
                },
                {
                  "name": "VM Network-2",
                  "vlan_id": 0
                },
                {
                  "name": "Data VM Network",
                  "vlan_id": 10
                }
              ]
            }
          ]
        },
        "system": {
          "system_time": {
            "enabled": true,
            "protocol": "NTP",
            "ntp_config": {
              "server": [
                {
                  "hostname": "0.pool.ntp.org",
                  "command": "SERVER"
                },
                {
                  "hostname": "1.pool.ntp.org",
                  "command": "SERVER"
                }
              ]
            }
          }
        }
      }
    }
